import { normalizePluginPattern } from './plugin-normalizer';

export type PluginCategory = 
  | 'Synth' 
  | 'Sampler' 
  | 'EQ' 
  | 'Compressor' 
  | 'Reverb' 
  | 'Delay' 
  | 'Saturation' 
  | 'Limiter' 
  | 'Analyzer' 
  | 'Creative' 
  | 'Vocal' 
  | 'Modulation' 
  | 'Utility' 
  | 'Mastering'
  | 'Distortion'
  | 'Filter'
  | 'Preamp'
  | 'Amplifier'
  | 'Other';

export interface KnownPlugin {
  brand: string;
  displayName: string;
  category: PluginCategory;
  subcategory?: string;
  aliases: string[]; // patterns normalisés (sortie de normalizePluginPattern)
}

export const KNOWN_PLUGINS: KnownPlugin[] = [
  // --- ARTURIA V COLLECTION & FX ---
  { brand: "Arturia", displayName: "Acid V", category: "Synth", aliases: ["acid_v"] },
  { brand: "Arturia", displayName: "Analog Lab V", category: "Synth", aliases: ["analog_lab_v", "analog_lab"] },
  { brand: "Arturia", displayName: "ARP 2600 V", category: "Synth", aliases: ["arp_2600_v", "arp_2600", "arp2600"] },
  { brand: "Arturia", displayName: "B-3 V", category: "Synth", aliases: ["b_3_v", "b3v", "b_3"] },
  { brand: "Arturia", displayName: "Buchla Easel V", category: "Synth", aliases: ["buchla_easel_v", "buchla"] },
  { brand: "Arturia", displayName: "Clavinet V", category: "Synth", aliases: ["clavinet_v", "clavinet"] },
  { brand: "Arturia", displayName: "CMI V", category: "Synth", aliases: ["cmi_v", "cmiv", "cmi"] },
  { brand: "Arturia", displayName: "CP-70 V", category: "Synth", aliases: ["cp_70_v", "cp70", "cp_70"] },
  { brand: "Arturia", displayName: "CS-80 V", category: "Synth", aliases: ["cs_80_v", "cs80", "cs_80"] },
  { brand: "Arturia", displayName: "CZ V", category: "Synth", aliases: ["cz_v", "czv", "cz"] },
  { brand: "Arturia", displayName: "DX7 V", category: "Synth", aliases: ["dx7_v", "dx7"] },
  { brand: "Arturia", displayName: "Emulator II V", category: "Synth", aliases: ["emulator_ii_v", "emulator_ii"] },
  { brand: "Arturia", displayName: "Farfisa V", category: "Synth", aliases: ["farfisa_v", "farfisa"] },
  { brand: "Arturia", displayName: "Jun-6 V", category: "Synth", aliases: ["jun_6_v", "jun6", "jun_6"] },
  { brand: "Arturia", displayName: "Jup-8 V", category: "Synth", aliases: ["jup_8_v", "jup8", "jup_8"] },
  { brand: "Arturia", displayName: "Jup-8000 V", category: "Synth", aliases: ["jup_8000_v", "jup8000", "jup_8_000"] },
  { brand: "Arturia", displayName: "KORG MS-20 V", category: "Synth", aliases: ["korg_ms_20_v", "korg_ms20", "korg_ms_20"] },
  { brand: "Arturia", displayName: "Matrix-12 V", category: "Synth", aliases: ["matrix_12_v", "matrix12", "matrix_12"] },
  { brand: "Arturia", displayName: "Mellotron V", category: "Synth", aliases: ["mellotron_v", "mellotron"] },
  { brand: "Arturia", displayName: "Mini V", category: "Synth", aliases: ["mini_v", "miniv", "mini"] },
  { brand: "Arturia", displayName: "MiniBrute V", category: "Synth", aliases: ["mini_brute_v", "minibrute", "mini_brute"] },
  { brand: "Arturia", displayName: "MiniFreak V", category: "Synth", aliases: ["mini_freak_v", "minifreak", "mini_freak"] },
  { brand: "Arturia", displayName: "Modular V", category: "Synth", aliases: ["modular_v", "modular"] },
  { brand: "Arturia", displayName: "OP-Xa V", category: "Synth", aliases: ["op_xa_v", "opxa", "op_xa"] },
  { brand: "Arturia", displayName: "Piano V", category: "Sampler", aliases: ["piano_v", "piano"] },
  { brand: "Arturia", displayName: "Prophet-5 V", category: "Synth", aliases: ["prophet_5_v", "prophet5", "prophet_5"] },
  { brand: "Arturia", displayName: "Prophet-VS V", category: "Synth", aliases: ["prophet_vs_v", "prophetvs", "prophet_vs"] },
  { brand: "Arturia", displayName: "SEM V", category: "Synth", aliases: ["sem_v", "sem"] },
  { brand: "Arturia", displayName: "Solina V", category: "Synth", aliases: ["solina_v", "solina"] },
  { brand: "Arturia", displayName: "SQ80 V", category: "Synth", aliases: ["sq80_v", "sq80"] },
  { brand: "Arturia", displayName: "Stage-73 V", category: "Synth", aliases: ["stage_73_v", "stage73", "stage_73"] },
  { brand: "Arturia", displayName: "Synclavier V", category: "Synth", aliases: ["synclavier_v", "synclavier"] },
  { brand: "Arturia", displayName: "Synthi V", category: "Synth", aliases: ["synthi_v", "synthi"] },
  { brand: "Arturia", displayName: "Synthx V", category: "Synth", aliases: ["synthx_v", "synthx"] },
  { brand: "Arturia", displayName: "VOX Continental V", category: "Synth", aliases: ["vox_continental_v", "vox_continental"] },
  { brand: "Arturia", displayName: "Vocoder V", category: "Synth", aliases: ["vocoder_v", "vocoder"] },
  { brand: "Arturia", displayName: "Wurli V", category: "Synth", aliases: ["wurli_v", "wurli"] },
  { brand: "Arturia", displayName: "Augmented GRAND PIANO", category: "Synth", aliases: ["augmented_grand_piano"] },
  { brand: "Arturia", displayName: "Augmented MALLETS", category: "Synth", aliases: ["augmented_mallets"] },
  { brand: "Arturia", displayName: "Augmented BRASS", category: "Synth", aliases: ["augmented_brass"] },
  { brand: "Arturia", displayName: "Augmented WOODWINDS", category: "Synth", aliases: ["augmented_woodwinds"] },
  { brand: "Arturia", displayName: "Augmented YANGTZE", category: "Synth", aliases: ["augmented_yangtze"] },
  { brand: "Arturia", displayName: "Bus FORCE", category: "Compressor", aliases: ["bus_force"] },
  { brand: "Arturia", displayName: "Bus EXCITER-104", category: "Creative", aliases: ["bus_exciter_104"] },
  { brand: "Arturia", displayName: "Bus PEAK", category: "Limiter", aliases: ["bus_peak"] },
  { brand: "Arturia", displayName: "Comp DIODE-609", category: "Compressor", aliases: ["comp_diode_609"] },
  { brand: "Arturia", displayName: "Comp VCA-65", category: "Compressor", aliases: ["comp_vca_65"] },
  { brand: "Arturia", displayName: "Comp FET-76", category: "Compressor", aliases: ["comp_fet_76"] },
  { brand: "Arturia", displayName: "Comp TUBE-STA", category: "Compressor", aliases: ["comp_tube_sta"] },
  { brand: "Arturia", displayName: "Delay TAPE-201", category: "Delay", aliases: ["delay_tape_201", "delay_tape"] },
  { brand: "Arturia", displayName: "Delay MEMORY-BRIGADE", category: "Delay", aliases: ["delay_memory_brigade", "delay_brigade"] },
  { brand: "Arturia", displayName: "Delay ETERNITY", category: "Delay", aliases: ["delay_eternity"] },
  { brand: "Arturia", displayName: "Dist COLDFIRE", category: "Distortion", aliases: ["dist_coldfire"] },
  { brand: "Arturia", displayName: "Dist OPAMP-21", category: "Distortion", aliases: ["dist_opamp_21"] },
  { brand: "Arturia", displayName: "Dist TUBE-CULTURE", category: "Distortion", aliases: ["dist_tube_culture"] },
  { brand: "Arturia", displayName: "Efx FRAGMENTS", category: "Creative", aliases: ["efx_fragments", "fragments"] },
  { brand: "Arturia", displayName: "Efx MOTIONS", category: "Creative", aliases: ["efx_motions"] },
  { brand: "Arturia", displayName: "Efx REFRACT", category: "Creative", aliases: ["efx_refract"] },
  { brand: "Arturia", displayName: "EQ SITRAL-295", category: "EQ", aliases: ["eq_sitral_295"] },
  { brand: "Arturia", displayName: "Filter MINI", category: "Filter", aliases: ["filter_mini"] },
  { brand: "Arturia", displayName: "Filter M12", category: "Filter", aliases: ["filter_m12"] },
  { brand: "Arturia", displayName: "Filter SEM", category: "Filter", aliases: ["filter_sem"] },
  { brand: "Arturia", displayName: "Filter MS-20", category: "Filter", aliases: ["filter_ms_20"] },
  { brand: "Arturia", displayName: "Flanger BL-20", category: "Modulation", aliases: ["flanger_bl_20"] },
  { brand: "Arturia", displayName: "Phaser BI-TRON", category: "Modulation", aliases: ["phaser_bi_tron"] },
  { brand: "Arturia", displayName: "Pre 1973", category: "Preamp", aliases: ["pre_1973"] },
  { brand: "Arturia", displayName: "Pre TridA", category: "Preamp", aliases: ["pre_trida"] },
  { brand: "Arturia", displayName: "Pre V76", category: "Preamp", aliases: ["pre_v76"] },
  { brand: "Arturia", displayName: "Rev INTENSITY", category: "Reverb", aliases: ["rev_intensity"] },
  { brand: "Arturia", displayName: "Rev PLATE-140", category: "Reverb", aliases: ["rev_plate_140"] },
  { brand: "Arturia", displayName: "Rev SPRING-636", category: "Reverb", aliases: ["rev_spring_636"] },
  { brand: "Arturia", displayName: "Rev LX-24", category: "Reverb", aliases: ["rev_lx_24"] },
  { brand: "Arturia", displayName: "Rotary CLS-222", category: "Modulation", aliases: ["rotary_cls_222"] },
  { brand: "Arturia", displayName: "Tape MELLO-FI", category: "Saturation", aliases: ["tape_mello_fi"] },
  { brand: "Arturia", displayName: "Chorus DIMENSION-D", category: "Modulation", aliases: ["chorus_dimension_d"] },
  { brand: "Arturia", displayName: "Chorus JUN-6", category: "Modulation", aliases: ["chorus_jun_6"] },

  // --- BRAINWORX / PLUGIN ALLIANCE ---
  { brand: "Brainworx", displayName: "bx_console SSL 4000 E", category: "Compressor", aliases: ["bx_console_ssl_4000_e"] },
  { brand: "Brainworx", displayName: "bx_console SSL 4000 G", category: "Compressor", aliases: ["bx_console_ssl_4000_g"] },
  { brand: "Brainworx", displayName: "bx_console SSL 9000 J", category: "Compressor", aliases: ["bx_console_ssl_9000_j"] },
  { brand: "Brainworx", displayName: "bx_console Focusrite SC", category: "Compressor", aliases: ["bx_console_focusrite_sc"] },
  { brand: "Brainworx", displayName: "bx_console AMEK 200", category: "Compressor", aliases: ["bx_console_amek_200", "bx_console_amek200"] },
  { brand: "Brainworx", displayName: "bx_console AMEK 9099", category: "Compressor", aliases: ["bx_console_amek_9099"] },
  { brand: "Brainworx", displayName: "bx_digital V3", category: "EQ", aliases: ["bx_digital_v3", "bx_digital", "bx_digital_mix"] },
  { brand: "Brainworx", displayName: "bx_masterdesk Pro", category: "Mastering", aliases: ["bx_masterdesk_pro", "bx_masterdesk"] },
  { brand: "Brainworx", displayName: "bx_masterdesk Classic", category: "Mastering", aliases: ["bx_masterdesk_classic"] },
  { brand: "Brainworx", displayName: "bx_limiter True Peak", category: "Limiter", aliases: ["bx_limiter_true_peak"] },
  { brand: "Brainworx", displayName: "bx_townhouse Buss Compressor", category: "Compressor", aliases: ["bx_townhouse_buss_compressor"] },
  { brand: "Brainworx", displayName: "bx_saturator V2", category: "Saturation", aliases: ["bx_saturator_v2"] },
  { brand: "Brainworx", displayName: "bx_refinement", category: "Utility", aliases: ["bx_refinement"] },
  { brand: "Brainworx", displayName: "bx_stereomaker", category: "Utility", aliases: ["bx_stereomaker"] },
  { brand: "Brainworx", displayName: "bx_subsynth", category: "Utility", aliases: ["bx_subsynth"] },
  { brand: "Brainworx", displayName: "bx_subfilter", category: "Utility", aliases: ["bx_subfilter"] },
  { brand: "Brainworx", displayName: "bx_solo", category: "Utility", aliases: ["bx_solo"] },
  { brand: "Brainworx", displayName: "bx_tuner", category: "Utility", aliases: ["bx_tuner"] },
  { brand: "Brainworx", displayName: "bx_meter", category: "Analyzer", aliases: ["bx_meter"] },
  { brand: "Brainworx", displayName: "bx_control V2", category: "Utility", aliases: ["bx_control"] },
  { brand: "Brainworx", displayName: "bx_delay2500", category: "Delay", aliases: ["bx_delay2500"] },
  { brand: "Brainworx", displayName: "bx_cleansweep Pro", category: "Filter", aliases: ["bx_cleansweep_pro"] },
  { brand: "Brainworx", displayName: "bx_clipper", category: "Limiter", aliases: ["bx_clipper"] },
  { brand: "Brainworx", displayName: "bx_oberhausen", category: "Synth", aliases: ["bx_oberhausen"] },
  { brand: "Brainworx", displayName: "bx_crispytuner", category: "Vocal", aliases: ["bx_crispytuner"] },
  { brand: "Brainworx", displayName: "bx_dynEQ V2", category: "EQ", aliases: ["bx_dyneq", "bx_dyn_eq", "bx_dyn_eq_mono"] },
  { brand: "Brainworx", displayName: "bx_enhancer", category: "Utility", aliases: ["bx_enhancer"] },
  { brand: "Brainworx", displayName: "bx_glue", category: "Compressor", aliases: ["bx_glue"] },
  { brand: "Brainworx", displayName: "bx_panEQ", category: "EQ", aliases: ["bx_paneq", "bx_pan_eq"] },
  { brand: "Brainworx", displayName: "bx_rooMS", category: "Reverb", aliases: ["bx_rooms", "bx_roo_ms"] },
  { brand: "Brainworx", displayName: "bx_shredspread", category: "Modulation", aliases: ["bx_shredspread"] },
  { brand: "Brainworx", displayName: "bx_XL V3", category: "Mastering", aliases: ["bx_xl"] },
  { brand: "Brainworx", displayName: "bx_rockrack V3", category: "Amplifier", aliases: ["bx_rockrack", "bx_rockrack_player"] },
  { brand: "Brainworx", displayName: "bx_blackdist2", category: "Distortion", aliases: ["bx_blackdist2"] },
  { brand: "Brainworx", displayName: "bx_bluechorus2", category: "Modulation", aliases: ["bx_bluechorus2"] },
  { brand: "Brainworx", displayName: "bx_boom V3", category: "Utility", aliases: ["bx_boom"] },
  { brand: "Brainworx", displayName: "bx_aura", category: "Modulation", aliases: ["bx_aura"] },
  { brand: "Brainworx", displayName: "bx_bassdude", category: "Amplifier", aliases: ["bx_bassdude"] },
  { brand: "Brainworx", displayName: "bx_distorange", category: "Distortion", aliases: ["bx_distorange"] },
  { brand: "Brainworx", displayName: "bx_greenscreamer", category: "Distortion", aliases: ["bx_greenscreamer"] },
  { brand: "Brainworx", displayName: "bx_megadual", category: "Amplifier", aliases: ["bx_megadual"] },
  { brand: "Brainworx", displayName: "bx_megasingle", category: "Amplifier", aliases: ["bx_megasingle"] },
  { brand: "Brainworx", displayName: "bx_metal2", category: "Distortion", aliases: ["bx_metal2"] },
  { brand: "Brainworx", displayName: "bx_opto Pedal", category: "Compressor", aliases: ["bx_opto_pedal", "bx_opto"] },
  { brand: "Brainworx", displayName: "bx_pulsar", category: "Modulation", aliases: ["bx_pulsar"] },
  { brand: "Brainworx", displayName: "bx_rockergain100", category: "Amplifier", aliases: ["bx_rockergain100"] },
  { brand: "Brainworx", displayName: "bx_hybrid V2", category: "EQ", aliases: ["bx_hybrid", "bx_hybrid_mix"] },
  { brand: "AMEK", displayName: "AMEK EQ 200", category: "EQ", aliases: ["amek_eq_200"] },
  { brand: "AMEK", displayName: "AMEK EQ 250", category: "EQ", aliases: ["amek_eq_250"] },
  { brand: "AMEK", displayName: "AMEK Mastering Compressor", category: "Compressor", aliases: ["amek_mastering_compressor"] },
  { brand: "Ampeg", displayName: "Ampeg SVT3Pro", category: "Amplifier", aliases: ["ampeg_svt3pro"] },
  { brand: "Ampeg", displayName: "Ampeg B15N", category: "Amplifier", aliases: ["ampeg_b15n"] },
  { brand: "Ampeg", displayName: "Ampeg SVTVR Classic", category: "Amplifier", aliases: ["ampeg_svtvr_classic", "ampeg_svtvr"] },
  { brand: "Ampeg", displayName: "Ampeg V4B", category: "Amplifier", aliases: ["ampeg_v4b"] },
  { brand: "ADA", displayName: "ADA Flanger", category: "Modulation", aliases: ["ada_flanger"] },
  { brand: "ADA", displayName: "ADA STD-1 Stereo Tapped Delay", category: "Delay", aliases: ["ada_std_1_stereo_tapped_delay", "ada_std1"] },
  { brand: "Bettermaker", displayName: "Bettermaker BM60", category: "Reverb", aliases: ["bettermaker_bm60"] },
  { brand: "Bettermaker", displayName: "Bettermaker Bus Compressor", category: "Compressor", aliases: ["bettermaker_bus_compressor"] },
  { brand: "Bettermaker", displayName: "Bettermaker C502V", category: "Compressor", aliases: ["bettermaker_c502v"] },
  { brand: "Bettermaker", displayName: "Bettermaker EQ232D", category: "EQ", aliases: ["bettermaker_eq232d"] },
  { brand: "Bettermaker", displayName: "Bettermaker Mastering Compressor", category: "Compressor", aliases: ["bettermaker_mastering_compressor"] },
  { brand: "Bettermaker", displayName: "Bettermaker Passive Equalizer", category: "EQ", aliases: ["bettermaker_passive_equalizer"] },
  { brand: "Black Box", displayName: "HG-2 MS", category: "Saturation", aliases: ["black_box_analog_design_hg_2ms", "hg2"] },
  { brand: "Black Box", displayName: "HG-2", category: "Saturation", aliases: ["black_box_analog_design_hg_2"] },
  { brand: "Black Box", displayName: "HG-Q", category: "EQ", aliases: ["black_box_analog_design_hg_q"] },
  { brand: "Shadow Hills", displayName: "Mastering Compressor Class A", category: "Compressor", aliases: ["shadow_hills_class_a_mastering_comp", "shadowhills"] },
  { brand: "Shadow Hills", displayName: "OptoMax", category: "Compressor", aliases: ["shadow_hills_optomax"] },
  { brand: "SPL", displayName: "Iron", category: "Compressor", aliases: ["spl_iron"] },
  { brand: "SPL", displayName: "PQ", category: "EQ", aliases: ["spl_pq"] },
  { brand: "SPL", displayName: "Passeq", category: "EQ", aliases: ["spl_passeq"] },
  { brand: "SPL", displayName: "Attacker Plus", category: "Utility", aliases: ["spl_attacker_plus"] },
  { brand: "SPL", displayName: "BiG", category: "Utility", aliases: ["spl_big"] },
  { brand: "SPL", displayName: "De-Esser Dual-Band", category: "Vocal", aliases: ["spl_de_esser_dual_band"] },
  { brand: "SPL", displayName: "De-Verb Plus", category: "Reverb", aliases: ["spl_de_verb_plus"] },
  { brand: "SPL", displayName: "DrumXchanger", category: "Utility", aliases: ["spl_drumxchanger"] },
  { brand: "SPL", displayName: "EQ Ranger Plus", category: "EQ", aliases: ["spl_eq_ranger_plus"] },
  { brand: "SPL", displayName: "Free Ranger", category: "EQ", aliases: ["spl_free_ranger"] },
  { brand: "SPL", displayName: "HawkEye", category: "Analyzer", aliases: ["spl_hawkeye"] },
  { brand: "SPL", displayName: "Machine Head", category: "Saturation", aliases: ["spl_machine_head"] },
  { brand: "SPL", displayName: "Mo-Verb Plus", category: "Reverb", aliases: ["spl_mo_verb_plus"] },
  { brand: "SPL", displayName: "TwinTube", category: "Saturation", aliases: ["spl_twintube"] },
  { brand: "SPL", displayName: "Vitalizer MK2-T", category: "Utility", aliases: ["spl_vitalizer_mk2_t"] },
  { brand: "SPL", displayName: "Vitalizer MK3-T", category: "Utility", aliases: ["spl_vitalizer_mk3_t"] },
  { brand: "elysia", displayName: "alpha compressor", category: "Compressor", aliases: ["elysia_alpha_compressor", "elysia_alpha", "elysia_alpha_master", "elysia_alpha_mix"] },
  { brand: "elysia", displayName: "karacter", category: "Distortion", aliases: ["elysia_karacter_master", "elysia_karacter", "elysia_karacter_mix"] },
  { brand: "elysia", displayName: "mpressor", category: "Compressor", aliases: ["elysia_mpressor"] },
  { brand: "elysia", displayName: "museq", category: "EQ", aliases: ["elysia_museq_master", "elysia_museq", "elysia_museq_mix"] },
  { brand: "elysia", displayName: "nvelope", category: "Utility", aliases: ["elysia_nvelope"] },
  { brand: "elysia", displayName: "phils cascade", category: "Saturation", aliases: ["elysia_phils_cascade"] },
  { brand: "elysia", displayName: "niveau filter", category: "Filter", aliases: ["elysia_niveau_filter"] },
  { brand: "NEOLD", displayName: "BIG AL", category: "Saturation", aliases: ["neold_big_al"] },
  { brand: "NEOLD", displayName: "OLDTIMER", category: "Compressor", aliases: ["neold_oldtimer"] },
  { brand: "NEOLD", displayName: "RZ062", category: "EQ", aliases: ["neold_rz062"] },
  { brand: "NEOLD", displayName: "U17", category: "Compressor", aliases: ["neold_u17"] },
  { brand: "NEOLD", displayName: "U2A", category: "Compressor", aliases: ["neold_u2a"] },
  { brand: "NEOLD", displayName: "V76U73", category: "Compressor", aliases: ["neold_v76u73"] },
  { brand: "NEOLD", displayName: "WARBLE", category: "Creative", aliases: ["neold_warble"] },
  { brand: "NEOLD", displayName: "WUNDERLICH", category: "Compressor", aliases: ["neold_wunderlich"] },
  { brand: "Unfiltered Audio", displayName: "Bass Mint", category: "Utility", aliases: ["unfiltered_audio_bass_mint"] },
  { brand: "Unfiltered Audio", displayName: "Battalion", category: "Synth", aliases: ["unfiltered_audio_battalion"] },
  { brand: "Unfiltered Audio", displayName: "Byome", category: "Creative", aliases: ["unfiltered_audio_byome"] },
  { brand: "Unfiltered Audio", displayName: "Dent 2", category: "Distortion", aliases: ["unfiltered_audio_dent_2"] },
  { brand: "Unfiltered Audio", displayName: "Fault", category: "Modulation", aliases: ["unfiltered_audio_fault"] },
  { brand: "Unfiltered Audio", displayName: "G8", category: "Utility", aliases: ["unfiltered_audio_g8"] },
  { brand: "Unfiltered Audio", displayName: "Indent 2", category: "Distortion", aliases: ["unfiltered_audio_indent_2"] },
  { brand: "Unfiltered Audio", displayName: "Instant Delay", category: "Delay", aliases: ["unfiltered_audio_instant_delay"] },
  { brand: "Unfiltered Audio", displayName: "LION", category: "Synth", aliases: ["unfiltered_audio_lion"] },
  { brand: "Unfiltered Audio", displayName: "lo-fi-af", category: "Creative", aliases: ["unfiltered_audio_lo_fi_af"] },
  { brand: "Unfiltered Audio", displayName: "Needlepoint", category: "Creative", aliases: ["unfiltered_audio_needlepoint"] },
  { brand: "Unfiltered Audio", displayName: "Sandman Pro", category: "Delay", aliases: ["unfiltered_audio_sandman_pro", "unfiltered_audio_sandman"] },
  { brand: "Unfiltered Audio", displayName: "Silo", category: "Reverb", aliases: ["unfiltered_audio_silo"] },
  { brand: "Unfiltered Audio", displayName: "SpecOps", category: "Creative", aliases: ["unfiltered_audio_spec_ops"] },
  { brand: "Unfiltered Audio", displayName: "Tails", category: "Reverb", aliases: ["unfiltered_audio_tails"] },
  { brand: "Unfiltered Audio", displayName: "Triad", category: "Creative", aliases: ["unfiltered_audio_triad"] },
  { brand: "Unfiltered Audio", displayName: "Zip", category: "Compressor", aliases: ["unfiltered_audio_zip"] },
  { brand: "Dangerous Music", displayName: "BAX EQ", category: "EQ", aliases: ["dangerous_bax_eq_master", "dangerous_bax_eq_mix"] },
  { brand: "Diezel", displayName: "Herbert", category: "Amplifier", aliases: ["diezel_herbert"] },
  { brand: "Diezel", displayName: "VH4", category: "Amplifier", aliases: ["diezel_vh4"] },
  { brand: "Friedman", displayName: "BE100", category: "Amplifier", aliases: ["friedman_be100"] },
  { brand: "Friedman", displayName: "Buxom Betty", category: "Amplifier", aliases: ["friedman_buxom_betty"] },
  { brand: "Friedman", displayName: "DS40", category: "Amplifier", aliases: ["friedman_ds40"] },
  { brand: "Fuchs", displayName: "Overdrive Supreme 50", category: "Amplifier", aliases: ["fuchs_overdrive_supreme_50"] },
  { brand: "Fuchs", displayName: "Train II", category: "Amplifier", aliases: ["fuchs_train_ii"] },
  { brand: "Gallien Krueger", displayName: "800RB", category: "Amplifier", aliases: ["gallien_krueger_800rb"] },
  { brand: "Harris Doyle", displayName: "Natalus DSCEQ", category: "EQ", aliases: ["harris_doyle_natalus_dsceq"] },
  { brand: "HUM Audio Devices", displayName: "LAAL", category: "Limiter", aliases: ["hum_audio_devices_laal"] },
  { brand: "Millennia", displayName: "TCL-2", category: "Compressor", aliases: ["millennia_tcl_2"] },
  { brand: "Millennia", displayName: "NSEQ-2", category: "EQ", aliases: ["millennia_nseq_2"] },
  { brand: "Noveltech", displayName: "Character", category: "Utility", aliases: ["noveltech_character"] },
  { brand: "Noveltech", displayName: "Vocal Enhancer", category: "Vocal", aliases: ["noveltech_vocal_enhancer"] },
  { brand: "Purple Audio", displayName: "MC 77", category: "Compressor", aliases: ["purple_audio_mc_77"] },
  { brand: "Suhr", displayName: "SE100", category: "Amplifier", aliases: ["suhr_se100"] },
  { brand: "Suhr", displayName: "PT100", category: "Amplifier", aliases: ["suhr_pt100"] },
  { brand: "Vertigo", displayName: "VSC-2", category: "Compressor", aliases: ["vertigo_vsc_2"] },
  { brand: "Vertigo", displayName: "VSM-3", category: "Saturation", aliases: ["vertigo_vsm_3"] },
  { brand: "Vertigo", displayName: "VSS-2", category: "Compressor", aliases: ["vertigo_vss_2"] },
  { brand: "Lindell Audio", displayName: "254E", category: "Compressor", aliases: ["lindell_254e"] },
  { brand: "Lindell Audio", displayName: "354E", category: "Compressor", aliases: ["lindell_354e"] },
  { brand: "Lindell Audio", displayName: "50 Buss", category: "Compressor", aliases: ["lindell_50_buss"] },
  { brand: "Lindell Audio", displayName: "50 Channel", category: "Compressor", aliases: ["lindell_50_channel"] },
  { brand: "Lindell Audio", displayName: "69 Buss", category: "Compressor", aliases: ["lindell_69_buss"] },
  { brand: "Lindell Audio", displayName: "69 Channel", category: "Compressor", aliases: ["lindell_69_channel"] },
  { brand: "Lindell Audio", displayName: "6X-500", category: "Preamp", aliases: ["lindell_6x_500"] },
  { brand: "Lindell Audio", displayName: "7X-500", category: "Compressor", aliases: ["lindell_7x_500"] },
  { brand: "Lindell Audio", displayName: "80 Bus", category: "Compressor", aliases: ["lindell_80_bus"] },
  { brand: "Lindell Audio", displayName: "80 Channel", category: "Compressor", aliases: ["lindell_80_channel"] },
  { brand: "Lindell Audio", displayName: "902 De-esser", category: "Vocal", aliases: ["lindell_902_de_esser"] },
  { brand: "Lindell Audio", displayName: "ChannelX", category: "Compressor", aliases: ["lindell_channel_x"] },
  { brand: "Lindell Audio", displayName: "EQ825", category: "EQ", aliases: ["lindell_eq825"] },
  { brand: "Lindell Audio", displayName: "MBC", category: "Compressor", aliases: ["lindell_mbc"] },
  { brand: "Lindell Audio", displayName: "MU-66", category: "Compressor", aliases: ["lindell_mu_66"] },
  { brand: "Lindell Audio", displayName: "PEX-500", category: "EQ", aliases: ["lindell_pex_500"] },
  { brand: "Lindell Audio", displayName: "SBC", category: "Compressor", aliases: ["lindell_sbc"] },
  { brand: "Lindell Audio", displayName: "TE-100", category: "EQ", aliases: ["lindell_te_100"] },

  // --- KILOHEARTS ---
  { brand: "Kilohearts", displayName: "Phase Plant", category: "Synth", aliases: ["phase_plant"] },
  { brand: "Kilohearts", displayName: "Multipass", category: "Creative", aliases: ["multipass"] },
  { brand: "Kilohearts", displayName: "Snap Heap", category: "Creative", aliases: ["snap_heap"] },
  { brand: "Kilohearts", displayName: "3-Band EQ", category: "EQ", aliases: ["k_hs_3_band_eq"] },
  { brand: "Kilohearts", displayName: "Bitcrush", category: "Distortion", aliases: ["k_hs_bitcrush"] },
  { brand: "Kilohearts", displayName: "Chorus", category: "Modulation", aliases: ["k_hs_chorus"] },
  { brand: "Kilohearts", displayName: "Compressor", category: "Compressor", aliases: ["k_hs_compressor"] },
  { brand: "Kilohearts", displayName: "Delay", category: "Delay", aliases: ["k_hs_delay"] },
  { brand: "Kilohearts", displayName: "Distortion", category: "Distortion", aliases: ["k_hs_distortion"] },
  { brand: "Kilohearts", displayName: "Dynamics", category: "Compressor", aliases: ["k_hs_dynamics"] },
  { brand: "Kilohearts", displayName: "Filter", category: "Filter", aliases: ["k_hs_filter"] },
  { brand: "Kilohearts", displayName: "Flanger", category: "Modulation", aliases: ["k_hs_flanger"] },
  { brand: "Kilohearts", displayName: "Frequency Shifter", category: "Creative", aliases: ["k_hs_frequency_shifter"] },
  { brand: "Kilohearts", displayName: "Gain", category: "Utility", aliases: ["k_hs_gain"] },
  { brand: "Kilohearts", displayName: "Gate", category: "Utility", aliases: ["k_hs_gate"] },
  { brand: "Kilohearts", displayName: "Haas", category: "Creative", aliases: ["k_hs_haas"] },
  { brand: "Kilohearts", displayName: "Limiter", category: "Limiter", aliases: ["k_hs_limiter"] },
  { brand: "Kilohearts", displayName: "Phaser", category: "Modulation", aliases: ["k_hs_phaser"] },
  { brand: "Kilohearts", displayName: "Pitch Shifter", category: "Creative", aliases: ["k_hs_pitch_shifter"] },
  { brand: "Kilohearts", displayName: "Reverb", category: "Reverb", aliases: ["k_hs_reverb"] },
  { brand: "Kilohearts", displayName: "Stereo", category: "Utility", aliases: ["k_hs_stereo"] },
  { brand: "Kilohearts", displayName: "Tape Stop", category: "Creative", aliases: ["k_hs_tape_stop"] },
  { brand: "Kilohearts", displayName: "Transient Shaper", category: "Utility", aliases: ["k_hs_transient_shaper"] },
  { brand: "Kilohearts", displayName: "Disperser", category: "Modulation", aliases: ["k_hs_disperser", "disperser"] },
  { brand: "Kilohearts", displayName: "Faturator", category: "Distortion", aliases: ["k_hs_faturator", "faturator"] },
  { brand: "Kilohearts", displayName: "Convolver", category: "Reverb", aliases: ["k_hs_convolver"] },
  { brand: "Kilohearts", displayName: "Channel Mixer", category: "Utility", aliases: ["k_hs_channel_mixer"] },
  { brand: "Kilohearts", displayName: "Comb Filter", category: "Filter", aliases: ["k_hs_comb_filter"] },
  { brand: "Kilohearts", displayName: "Dual Delay", category: "Delay", aliases: ["k_hs_dual_delay"] },
  { brand: "Kilohearts", displayName: "Clipper", category: "Limiter", aliases: ["k_hs_clipper"] },
  { brand: "Kilohearts", displayName: "Ensemble", category: "Modulation", aliases: ["k_hs_ensemble"] },
  { brand: "Kilohearts", displayName: "Compactor", category: "Compressor", aliases: ["k_hs_compactor"] },
  { brand: "Kilohearts", displayName: "Formant Filter", category: "Filter", aliases: ["k_hs_formant_filter"] },
  { brand: "Kilohearts", displayName: "Ladder Filter", category: "Filter", aliases: ["k_hs_ladder_filter"] },
  { brand: "Kilohearts", displayName: "Nonlinear Filter", category: "Filter", aliases: ["k_hs_nonlinear_filter"] },
  { brand: "Kilohearts", displayName: "Phase Distortion", category: "Distortion", aliases: ["k_hs_phase_distortion"] },
  { brand: "Kilohearts", displayName: "Resonator", category: "Filter", aliases: ["k_hs_resonator"] },
  { brand: "Kilohearts", displayName: "Reverser", category: "Creative", aliases: ["k_hs_reverser"] },
  { brand: "Kilohearts", displayName: "Ring Mod", category: "Modulation", aliases: ["k_hs_ring_mod"] },
  { brand: "Kilohearts", displayName: "Shaper", category: "Distortion", aliases: ["k_hs_shaper"] },
  { brand: "Kilohearts", displayName: "Trance Gate", category: "Creative", aliases: ["k_hs_trance_gate"] },

  // --- TONEBOOSTERS ---
  { brand: "ToneBoosters", displayName: "Barricade", category: "Limiter", aliases: ["tb_barricade"] },
  { brand: "ToneBoosters", displayName: "Compressor", category: "Compressor", aliases: ["tb_compressor"] },
  { brand: "ToneBoosters", displayName: "Equalizer", category: "EQ", aliases: ["tb_equalizer", "tb_equalizer_pro"] },
  { brand: "ToneBoosters", displayName: "Reverb", category: "Reverb", aliases: ["tb_reverb"] },
  { brand: "ToneBoosters", displayName: "ReelBus", category: "Saturation", aliases: ["tb_reelbus"] },
  { brand: "ToneBoosters", displayName: "Morphit", category: "Utility", aliases: ["tb_morphit"] },
  { brand: "ToneBoosters", displayName: "Enhancer", category: "Utility", aliases: ["tb_enhancer"] },
  { brand: "ToneBoosters", displayName: "BitJuggler", category: "Distortion", aliases: ["tb_bit_juggler"] },
  { brand: "ToneBoosters", displayName: "Flowtones", category: "Synth", aliases: ["tb_flowtones"] },
  { brand: "ToneBoosters", displayName: "VoicePitcher", category: "Vocal", aliases: ["tb_voice_pitcher"] },
  { brand: "ToneBoosters", displayName: "DualVCF", category: "Filter", aliases: ["tb_dual_vcf"] },
  { brand: "ToneBoosters", displayName: "GonioMeter", category: "Analyzer", aliases: ["tb_gonio_meter"] },
  { brand: "ToneBoosters", displayName: "Lowtone", category: "Synth", aliases: ["tb_lowtone"] },
  { brand: "ToneBoosters", displayName: "MBC", category: "Compressor", aliases: ["tb_mbc"] },
  { brand: "ToneBoosters", displayName: "Sibalance", category: "Vocal", aliases: ["tb_sibalance"] },
  { brand: "ToneBoosters", displayName: "Spectrogram", category: "Analyzer", aliases: ["tb_spectrogram"] },

  // --- NATIVE INSTRUMENTS ---
  { brand: "Native Instruments", displayName: "Massive", category: "Synth", aliases: ["massive"] },
  { brand: "Native Instruments", displayName: "Massive X", category: "Synth", aliases: ["massive_x"] },
  { brand: "Native Instruments", displayName: "FM8", category: "Synth", aliases: ["fm8"] },
  { brand: "Native Instruments", displayName: "Kontakt 7", category: "Sampler", aliases: ["kontakt_7", "kontakt"] },
  { brand: "Native Instruments", displayName: "Kontakt 8", category: "Sampler", aliases: ["kontakt_8"] },
  { brand: "Native Instruments", displayName: "Battery 4", category: "Sampler", aliases: ["battery_4", "battery"] },
  { brand: "Native Instruments", displayName: "Reaktor 6", category: "Sampler", aliases: ["reaktor_6", "reaktor"] },
  { brand: "Native Instruments", displayName: "Guitar Rig 7", category: "Creative", aliases: ["guitar_rig_7", "guitar_rig"] },
  { brand: "Native Instruments", displayName: "Komplete Kontrol", category: "Utility", aliases: ["komplete_kontrol"] },
  { brand: "Native Instruments", displayName: "Bite", category: "Distortion", aliases: ["bite"] },
  { brand: "Native Instruments", displayName: "Dirt", category: "Distortion", aliases: ["dirt"] },
  { brand: "Native Instruments", displayName: "Freak", category: "Creative", aliases: ["freak"] },
  { brand: "Native Instruments", displayName: "Driver", category: "Filter", aliases: ["driver"] },
  { brand: "Native Instruments", displayName: "Enhanced EQ", category: "EQ", aliases: ["enhanced_eq"] },
  { brand: "Native Instruments", displayName: "Passive EQ", category: "EQ", aliases: ["passive_eq"] },
  { brand: "Native Instruments", displayName: "Vari Comp", category: "Compressor", aliases: ["vari_comp"] },

  // --- FABFILTER ---
  { brand: "FabFilter", displayName: "Pro-Q 4", category: "EQ", aliases: ["fabfilter_pro_q_4", "pro_q_4"] },
  { brand: "FabFilter", displayName: "Pro-Q 3", category: "EQ", aliases: ["fabfilter_pro_q_3", "pro_q_3"] },
  { brand: "FabFilter", displayName: "Pro-C 2", category: "Compressor", aliases: ["fabfilter_pro_c_2", "pro_c_2"] },
  { brand: "FabFilter", displayName: "Pro-L 2", category: "Limiter", aliases: ["fabfilter_pro_l_2", "pro_l_2"] },
  { brand: "FabFilter", displayName: "Pro-R 2", category: "Reverb", aliases: ["fabfilter_pro_r_2", "pro_r_2"] },
  { brand: "FabFilter", displayName: "Saturn 2", category: "Saturation", aliases: ["fabfilter_saturn_2", "saturn_2"] },
  { brand: "FabFilter", displayName: "Timeless 3", category: "Delay", aliases: ["fabfilter_timeless_3", "timeless_3"] },
  { brand: "FabFilter", displayName: "Twin 3", category: "Synth", aliases: ["fabfilter_twin_3", "twin_3"] },
  { brand: "FabFilter", displayName: "Volcano 3", category: "Filter", aliases: ["fabfilter_volcano_3", "volcano_3"] },
  { brand: "FabFilter", displayName: "Pro-MB", category: "Compressor", aliases: ["fabfilter_pro_mb", "pro_mb"] },
  { brand: "FabFilter", displayName: "Pro-DS", category: "Utility", aliases: ["fabfilter_pro_ds", "pro_ds"] },
  { brand: "FabFilter", displayName: "Pro-G", category: "Utility", aliases: ["fabfilter_pro_g", "pro_g"] },

  // --- IZOTOPE ---
  { brand: "iZotope", displayName: "Ozone 12 Equalizer", category: "EQ", aliases: ["ozone_12_equalizer"] },
  { brand: "iZotope", displayName: "Ozone Imager 2", category: "Utility", aliases: ["ozone_imager_2"] },
  { brand: "iZotope", displayName: "Vocal Doubler", category: "Vocal", aliases: ["vocal_doubler"] },
  { brand: "iZotope", displayName: "Vinyl", category: "Saturation", aliases: ["vinyl"] },
  { brand: "iZotope", displayName: "Neutron 4", category: "Compressor", aliases: ["neutron_4"] },
  { brand: "iZotope", displayName: "RX 10", category: "Utility", aliases: ["rx_10"] },

  // --- SOUNDTOYS ---
  { brand: "Soundtoys", displayName: "Decapitator", category: "Saturation", aliases: ["decapitator"] },
  { brand: "Soundtoys", displayName: "EchoBoy", category: "Delay", aliases: ["echoboy"] },
  { brand: "Soundtoys", displayName: "Little AlterBoy", category: "Vocal", aliases: ["little_alterboy", "alterboy"] },

  // --- VALHALLA ---
  { brand: "Valhalla DSP", displayName: "VintageVerb", category: "Reverb", aliases: ["valhalla_vintage_verb", "vintageverb"] },
  { brand: "Valhalla DSP", displayName: "ValhallaRoom", category: "Reverb", aliases: ["valhalla_room", "valhallaroom"] },
  { brand: "Valhalla DSP", displayName: "ValhallaDelay", category: "Delay", aliases: ["valhalla_delay", "valhalladelay"] },
  { brand: "Valhalla DSP", displayName: "ValhallaSupermassive", category: "Reverb", aliases: ["valhalla_supermassive", "supermassive"] },
  { brand: "Valhalla DSP", displayName: "ValhallaFutureVerb", category: "Reverb", aliases: ["valhalla_future_verb", "futureverb"] },
  { brand: "Valhalla DSP", displayName: "ValhallaFreqEcho", category: "Delay", aliases: ["valhalla_freq_echo", "freqecho"] },

  // --- VARIOUS ---
  { brand: "Xfer Records", displayName: "Serum", category: "Synth", aliases: ["serum"] },
  { brand: "Xfer Records", displayName: "OTT", category: "Compressor", aliases: ["ott"] },
  { brand: "Vital Audio", displayName: "Vital", category: "Synth", aliases: ["vital"] },
  { brand: "LennarDigital", displayName: "Sylenth1", category: "Synth", aliases: ["sylenth1"] },
  { brand: "Antares", displayName: "Auto-Tune Access", category: "Vocal", aliases: ["auto_tune_access"] },
  { brand: "Antares", displayName: "Auto-Tune EFX", category: "Vocal", aliases: ["auto_tune_efx"] },
  { brand: "Antares", displayName: "Auto-Tune", category: "Vocal", aliases: ["auto_tune"] },
  { brand: "Antares", displayName: "Auto-Key", category: "Utility", aliases: ["auto_key"] },
  { brand: "LTL", displayName: "Chop Shop EQ", category: "EQ", aliases: ["ltl_chop_shop_eq"] },
  { brand: "LTL", displayName: "Silver Bullet mk2", category: "Saturation", aliases: ["ltl_silver_bullet_mk2"] },
  { brand: "Looptrotter", displayName: "SA2RATE2", category: "Saturation", aliases: ["looptrotter_sa2rate2"] },
  { brand: "MAAT", displayName: "GON", category: "Analyzer", aliases: ["maat_gon"] },
  { brand: "NeuralNote", displayName: "NeuralNote", category: "Utility", aliases: ["neural_note"] },
  { brand: "noteGRABBER", displayName: "noteGRABBER", category: "Utility", aliases: ["notegrabber"] },
  { brand: "ROLI", displayName: "Studio Drums", category: "Sampler", aliases: ["roli_studio_drums"] },
  { brand: "ROLI", displayName: "Studio Player", category: "Sampler", aliases: ["roli_studio_player"] },
  { brand: "Sonnox", displayName: "ListenHub", category: "Utility", aliases: ["listenhub"] },
  { brand: "TBTECH", displayName: "Kirchhoff-EQ", category: "EQ", aliases: ["tbtech_kirchhoff_eq"] },
  { brand: "TBTECH", displayName: "Cenozoix Compressor", category: "Compressor", aliases: ["tbtech_cenozoix_compressor"] },
  { brand: "UVI", displayName: "UVIWorkstation", category: "Sampler", aliases: ["uvi_workstation", "uviworkstation"] },
  { brand: "Kiive Audio", displayName: "Tape Face", category: "Saturation", aliases: ["kiive_tape_face"] },
  { brand: "Kiive Audio", displayName: "XTComp", category: "Compressor", aliases: ["kiive_xtcomp"] },
  { brand: "Swivel Audio", displayName: "BDE", category: "Distortion", aliases: ["swivel_audio_bde", "bde"] },
  { brand: "Swivel Audio", displayName: "Click Boom", category: "Creative", aliases: ["swivel_audio_click_boom"] },
  { brand: "Swivel Audio", displayName: "HitStrip", category: "Creative", aliases: ["swivel_audio_hit_strip"] },
  { brand: "Swivel Audio", displayName: "Knocktonal", category: "EQ", aliases: ["swivel_audio_knocktonal"] },
  { brand: "Swivel Audio", displayName: "Spread", category: "Creative", aliases: ["swivel_audio_spread"] },
  { brand: "Swivel Audio", displayName: "The Sauce", category: "Creative", aliases: ["swivel_audio_the_sauce"] },
  { brand: "Aberrant DSP", displayName: "BEAM", category: "Creative", aliases: ["beam_filter", "beam_haze"] },
  { brand: "dearVR", displayName: "dearVR PRO", category: "Creative", aliases: ["dear_vr_pro", "dear_vr_pro_2"] },
  { brand: "Kazrog", displayName: "KClip", category: "Limiter", aliases: ["kclip_zero", "kclip"] },
  { brand: "Ujam", displayName: "BEATMAKER", category: "Sampler", aliases: ["beatmaker"] },
  { brand: "Ujam", displayName: "FIN-BOOST", category: "Utility", aliases: ["fin_boost"] },
  { brand: "Ujam", displayName: "FIN-DYNAMO", category: "Utility", aliases: ["fin_dynamo"] },
  { brand: "Ujam", displayName: "USYNTH", category: "Synth", aliases: ["usynth"] },
  { brand: "DS Audio", displayName: "Thorn", category: "Synth", aliases: ["ds_thorn", "thorn"] },
  { brand: "DS Audio", displayName: "Tantra", category: "Creative", aliases: ["ds_tantra"] },
  { brand: "ENGL", displayName: "E646 VS", category: "Amplifier", aliases: ["engl_e646_vs"] },
  { brand: "ENGL", displayName: "E765 RT", category: "Amplifier", aliases: ["engl_e765_rt"] },
  { brand: "ENGL", displayName: "Savage 120", category: "Amplifier", aliases: ["engl_savage_120"] },
  { brand: "Fiedler Audio", displayName: "Splat", category: "Distortion", aliases: ["fiedler_audio_splat"] },
  { brand: "Fiedler Audio", displayName: "Stage", category: "Creative", aliases: ["fiedler_audio_stage"] },
  { brand: "Chandler Limited", displayName: "GAV19T", category: "Amplifier", aliases: ["chandler_gav19t"] },
  { brand: "Black Box", displayName: "HG-Q", category: "EQ", aliases: ["black_box_analog_design_hg_q"] },
  { brand: "Hears", displayName: "Perfection", category: "Saturation", aliases: ["hears_perfection"] },
  { brand: "Acme Audio", displayName: "Opticom XLA-3", category: "Compressor", aliases: ["acme_opticom_xla_3"] },
  { brand: "7DeadlySnares", displayName: "7DeadlySnares", category: "Sampler", aliases: ["7deadly_snares"] },
  { brand: "RANDOM", displayName: "Metal", category: "Creative", aliases: ["random_metal"] },
  { brand: "RipX", displayName: "RipLink", category: "Utility", aliases: ["rip_link"] },
  { brand: "Cut Classic", displayName: "High Flyer", category: "Creative", aliases: ["cut_classic_high_flyer"] },
];

// En bas de plugin-knowledge.ts
if (process.env.NODE_ENV === 'development') {
  for (const plugin of KNOWN_PLUGINS) {
    for (const alias of plugin.aliases) {
      const normalized = normalizePluginPattern(alias);
      if (normalized !== alias) {
        // eslint-disable-next-line no-console
        console.warn(
          `[plugin-knowledge] Alias "${alias}" for ${plugin.displayName} is not canonical. ` +
          `Expected: "${normalized}". Please update the dictionary entry.`
        );
      }
    }
  }
}
